const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "LevsArt",
   "filename": "levsArt.txt",
   "credit_text": "Lev Roland-Kalb",
   "credit_url": "https://github.com/Levrk/PYTHON-RPG"},
  {"title": "Car",
   "filename": "car_art.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
];
